feat(op): User-configurable claims_supported
zitadel/oidc pull request #495
Opened 2023-12-04 20:33 UTC by snowkat

This change adds a new `SupportedClaims` field to `op.Config` along with `(op.Configuration).SupportedClaims()`, in order to applications to define what claims they support in discovery.

To retain compatibility with the existing system, `(op.Config).SupportedClaims` can be nil, in which case `(op.Config).SupportedClaims()` returns `DefaultSupportedClaims`&mdash;which corresponds to the hardcoded values previously returned.

`op.SupportedClaims(c Configuration)` exists for compatibility as well&mdash;since it's exported, I don't want to assume it's unused by some application&mdash;but can be deprecated.

### Definition of Ready

- [X] I am happy with the code
- [X] Short description of the feature/issue is added in the pr description
- [ ] PR is linked to the corresponding user story
- [ ] Acceptance criteria are met
- [ ] All open todos and follow ups are defined in a new ticket and justified
- [ ] Deviations from the acceptance criteria and design are agreed with the PO and documented.
- [X] No debug or dead code
- [X] My code has no repetitions
- [X] Critical parts are tested automatically
- [X] Where possible E2E tests are implemented
- [ ] Documentation/examples are up-to-date
- [ ] All non-functional requirements are met
- [ ] Functionality of the acceptance criteria is checked manually on the dev system.

2023-12-05 15:29 UTC, muhlemmer requested changes
Thanks for the contribution!

We prefer to avoid breaking changes in the interfaces unless we are aiming for a new major release.

I let some comments on how to prevent this breaking change.

2023-12-05 15:29 UTC, muhlemmer commented on pkg/op/config.go
> +	SupportedClaims() []string
Adding a method to the interface would be a breaking change, instead we should use the global function.

2023-12-05 15:29 UTC, muhlemmer commented on pkg/op/discovery.go
>  		CodeChallengeMethodsSupported:                      CodeChallengeMethods(config),
```suggestion
		ClaimsSupported:                                    SupportedClaims(config),
```

2023-12-05 15:29 UTC, muhlemmer commented on pkg/op/discovery.go
>  		CodeChallengeMethodsSupported:                      CodeChallengeMethods(config),
```suggestion
		ClaimsSupported:                                    SupportedClaims(config),
```

2023-12-05 15:29 UTC, muhlemmer commented on pkg/op/discovery.go
>  }
```suggestion
func SupportedClaims(c Configuration) []string {
	provider, ok := c.(*Provider)
	if ok && provider.config.SupportedClaims != nil {
		return provider.config.SupportedClaims
	}

	return DefaultSupportedClaims
}
```

2023-12-05 15:29 UTC, muhlemmer commented on pkg/op/op.go
> +}
Remove unneeded method

2023-12-05 19:16 UTC, snowkat commented
Thanks for the suggestion. I've updated the interface and `op.SupportedClaims`, and reverted my change to the relevant test.

2023-12-17 12:06 UTC, muhlemmer approved these changes

2023-12-17 12:06 UTC, merged